# Generated by Django 5.0.3 on 2024-04-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
